[package]
name = "worms_server"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.74"
dashmap = "6.1.0"
encoding_rs = "0.8.33"
tokio = { version = "1.34.0", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["full"] }
log = "0.4.20"
futures = "0.3.31"
futures-util = { version = "0.3.29", features = ["tokio-io", "async-await", "sink", "default"] }
pretty_env_logger = "0.5.0"
rustc-hash = "2.0.0"
nohash-hasher = "0.2.0"
clap = { version = "4.5.20", features = ["default", "derive"] }
bitflags = "2.6.0"
dotenv = "0.15.0"

[profile.release]
opt-level = 3
debug = false
lto = "fat"
codegen-units = 1